apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: clone
      runAfter:
        - cleanup
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/sachiyology/ci-cd-final-project.git
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: output

    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: test
      runAfter:
        - lint
      taskRef:
        name: nose